<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<jsp:include page="/WEB-INF/jsp/fragments/header.jsp"><jsp:param name="title" value="Inventory"/><jsp:param name="active" value="inventory"/><jsp:param name="breadcrumb" value="Inventory"/></jsp:include>
<div class="page-heading"><div><p class="eyebrow">CATALOG</p><h1>Inventory</h1><p class="muted">Manage products, prices, and on-hand stock.</p></div><a class="button button-primary" href="${pageContext.request.contextPath}/inventory/add"><span>＋</span> Add product</a></div>
<section class="panel"><div class="section-heading"><div><h2>All products <span class="count-badge">${products.size()}</span></h2></div><label class="search-box"><span>⌕</span><input type="search" id="inventory-search" placeholder="Find a product" aria-label="Find a product"></label></div>
  <c:choose><c:when test="${not empty products}"><div class="table-wrap"><table id="inventory-table"><thead><tr><th>Product</th><th>Category</th><th>Unit price</th><th>In stock</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><c:forEach items="${products}" var="product"><tr data-search="${product.name} ${product.category}"><td><strong><c:out value="${product.name}"/></strong></td><td><c:out value="${empty product.category ? '—' : product.category}"/></td><td class="money">₹<fmt:formatNumber value="${product.price}" minFractionDigits="2" maxFractionDigits="2" groupingUsed="true"/></td><td><span class="stock-pill ${product.stock <= 5 ? 'low' : ''}">${product.stock}</span></td><td class="actions"><a class="icon-button" href="${pageContext.request.contextPath}/inventory/${product.id}/edit" aria-label="Edit ${product.name}" title="Edit product">✎</a><form method="post" action="${pageContext.request.contextPath}/inventory/${product.id}/delete" data-confirm="Remove ${product.name} from inventory?"><button class="icon-button danger" type="submit" aria-label="Remove ${product.name}" title="Remove product">×</button></form></td></tr></c:forEach></tbody></table><p class="no-results" id="no-results" hidden>No products match that search.</p></div></c:when><c:otherwise><div class="empty-state"><span class="empty-mark">▤</span><strong>Your inventory is empty</strong><p>Add your first product to start tracking stock.</p><a class="button button-secondary" href="${pageContext.request.contextPath}/inventory/add">Add a product</a></div></c:otherwise></c:choose>
</section>
<script src="${pageContext.request.contextPath}/js/inventory.js" defer></script>
<jsp:include page="/WEB-INF/jsp/fragments/footer.jsp"/>